apiVersion: apps/v1
kind: Deployment
metadata:
  name: kg
  namespace: utility
  labels:
    app: kg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kg
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: kg
    spec:
      containers:
        - name: kg
          image: 10.3.7.221:5000/kg:<VERSION>
          ports:
            - containerPort: 5081
          env:
          - name: env
            value: "dev"
      nodeSelector:
        namespace: utility
---
apiVersion: v1
kind: Service
metadata:
  name: kg
  namespace: utility
  labels:
    app: kg
spec:
  ports:
  - name: http
    port: 5081
    targetPort: 5081
  selector:
    app: kg
  type: LoadBalancer
